export const LOAD_FORMATS_SUCCESS = 'LOAD_FORMATS_SUCCESS';
export const UPDATE_FORMAT_SUCCESS = 'UPDATE_FORMAT_SUCCESS';
export const CREATE_FORMAT_SUCCESS = 'CREATE_FORMAT_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
